INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('120-83-2', '2,4-Dichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Disinfectant", "Herbicide intermediate", "2,4-D metabolite"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('87-65-0', '2,6-Dichlorophenol', '[""]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('591-35-5', '3,5-Dichlorophenol', '[""]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('95-95-4', '2,4,5-Trichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption, dioxin contamination', '["Industrial intermediate", "Herbicide manufacturing byproduct"]', '["dermal", "ingestion"]', 'moderate', 'Industrial chemical', '{}'),
('88-06-2', '2,4,6-Trichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Wood preservative", "Disinfectant"]', '["dermal", "ingestion"]', 'moderate', 'Industrial chemical', '{}'),
('1163-19-5', 'PBDE-209', '["Decabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurodevelopmental effects', '["Flame retardant in electronics", "Textiles", "Building materials"]', '["ingestion", "inhalation", "dermal"]', 'very high', 'Phased out in US (2013)', '{}'),
('32536-52-0', 'PBDE-153', '["2,2,4,4,5,5-Hexabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity', '["Flame retardants", "House dust"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('182346-21-0', 'PBDE-183', '["2,2,3,4,4,5,6-Heptabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Flame retardants"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('68631-49-2', 'PBDE-100', '["2,2,4,4,6-Pentabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Flame retardants", "Furniture", "Electronics"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('446-72-0', 'Genistein', '[""]', 'Phytoestrogen (isoflavone)', 'confirmed', '["reproductive"]', 'Estrogenic effects, beneficial and adverse effects', '["Soy products", "Legumes", "Supplements"]', '["ingestion"]', 'low', 'Natural compound, dietary supplement', '{"beneficial": "May have health benefits at moderate doses"}');