INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('57-63-6', 'Ethinylestradiol', '["EE2", "17α-ethinylestradiol"]', 'Synthetic estrogen', 'confirmed', '["reproductive"]', 'Potent estrogenic effects, feminization of aquatic wildlife', '["Birth control pills", "Hormone therapy", "Wastewater"]', '["ingestion"]', 'moderate', 'Pharmaceutical, environmental concern', '{"aquatic_toxicity": "Extremely potent in fish"}'),
('50-28-2', 'Estradiol', '["17β-estradiol", "E2"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion"]', 'moderate', 'Natural hormone, pharmaceutical', '{}'),
('53-16-7', 'Estrone', '["E1"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion"]', 'moderate', 'Natural hormone', '{}'),
('50-27-1', 'Estriol', '["E3"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Weak estrogenic effects', '["Hormone therapy", "Pregnancy"]', '["ingestion"]', 'low', 'Natural hormone', '{}'),
('56-53-1', 'Diethylstilbestrol', '["DES"]', 'Synthetic estrogen', 'confirmed', '["reproductive"]', 'Potent estrogenic effects, transgenerational effects, cancer risk', '["Historical pharmaceutical (banned)", "Environmental contamination"]', '["ingestion"]', 'moderate', 'Banned in US (1971), known human carcinogen', '{"historical": "Caused reproductive abnormalities in offspring"}'),
('58-22-0', 'Testosterone', '[""]', 'Androgen', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion", "dermal"]', 'moderate', 'Controlled substance, pharmaceutical', '{}'),
('434-22-0', 'Nandrolone', '["19-nortestosterone"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic and anabolic effects', '["Performance-enhancing drugs", "Veterinary use"]', '["ingestion", "injection"]', 'moderate', 'Controlled substance', '{}'),
('521-18-6', 'Stanozolol', '["Winstrol"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Performance-enhancing drugs"]', '["ingestion"]', 'moderate', 'Controlled substance', '{}'),
('57-85-2', 'Testosterone propionate', '[""]', 'Androgen', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Hormone therapy", "Veterinary use"]', '["injection", "dermal"]', 'moderate', 'Controlled substance', '{}'),
('846-48-0', 'Boldenone', '["Equipoise"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Veterinary use", "Performance enhancement"]', '["injection"]', 'moderate', 'Controlled substance', '{}');