INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('72-20-8', 'Endrin', '[""]', 'Organochlorine insecticide', 'confirmed', '["reproductive"]', 'Reproductive toxicity, neurotoxicity', '["Banned pesticide", "Environmental persistence"]', '["ingestion", "dermal"]', 'very high', 'Banned in US (1986), Stockholm Convention POP', '{}'),
('58-89-9', 'Lindane', '["γ-HCH", "Gamma-hexachlorocyclohexane"]', 'Organochlorine insecticide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption, neurotoxicity', '["Banned pesticide", "Head lice treatment (historical)", "Environmental contamination"]', '["dermal", "ingestion", "inhalation"]', 'high', 'Banned in US (2006), Stockholm Convention POP', '{}'),
('8001-35-2', 'Toxaphene', '["Camphechlor"]', 'Organochlorine insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, cancer risk', '["Banned pesticide", "Environmental persistence"]', '["ingestion", "dermal", "inhalation"]', 'very high', 'Banned in US (1990), Stockholm Convention POP', '{}'),
('72-43-5', 'Methoxychlor', '["DMDT"]', 'Organochlorine insecticide', 'confirmed', '["reproductive"]', 'Estrogenic effects, reproductive toxicity', '["Banned pesticide", "DDT substitute"]', '["ingestion", "dermal"]', 'moderate', 'Cancelled in US (2003)', '{}'),
('115-29-7', 'Endosulfan', '["Thiodan"]', 'Organochlorine insecticide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption', '["Banned pesticide", "Agricultural use (historical)"]', '["dermal", "ingestion", "inhalation"]', 'high', 'Banned in US (2016), Stockholm Convention POP', '{}');INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('94-75-7', '2,4-Dichlorophenoxyacetic acid', '["2,4-D"]', 'Herbicide', 'suspected', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Herbicide", "Lawn care", "Agricultural use"]', '["dermal", "ingestion", "inhalation"]', 'low', 'EPA registered herbicide, controversial', '{}'),
('93-76-5', '2,4,5-Trichlorophenoxyacetic acid', '["2,4,5-T"]', 'Herbicide', 'confirmed', '["reproductive"]', 'Reproductive toxicity, dioxin contamination', '["Banned herbicide", "Agent Orange component"]', '["dermal", "ingestion"]', 'moderate', 'Banned in US (1985)', '{}'),
('1912-24-9', 'Atrazine', '[""]', 'Triazine herbicide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption, feminization in amphibians', '["Herbicide", "Agricultural use", "Water contamination"]', '["ingestion", "dermal", "inhalation"]', 'moderate', 'EPA registered, banned in EU', '{"controversy": "Widespread water contamination"}'),
('2921-88-2', 'Chlorpyrifos', '["Dursban", "Lorsban"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurodevelopmental toxicity, thyroid disruption', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'Banned for residential use (2001), food use cancelled (2021)', '{}'),
('333-41-5', 'Diazinon', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Residential use banned (2004)', '{}');INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('56-38-2', 'Parathion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Severe neurotoxicity, thyroid disruption', '["Banned pesticide", "Agricultural use (historical)"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Banned in US (2003)', '{}'),
('298-00-0', 'Methyl parathion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Neurotoxicity, thyroid effects', '["Banned pesticide"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Banned in US (2006)', '{}'),
('52-68-6', 'Trichlorfon', '["Dipterex"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Veterinary use"]', '["dermal", "ingestion", "inhalation"]', 'low', 'EPA registered', '{}'),
('62-73-7', 'Dichlorvos', '["DDVP"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects, neurotoxicity', '["Insecticide", "Pest strips", "Agricultural use"]', '["inhalation", "dermal", "ingestion"]', 'low', 'EPA registered, restricted use', '{}'),
('2104-64-5', 'EPN', '["O-Ethyl O-4-nitrophenyl phenylphosphonothioate"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Neurotoxicity, thyroid effects', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation"]', 'moderate', 'EPA registered, restricted use', '{}');INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('298-02-2', 'Phorate', '["Thimet"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Severe neurotoxicity, thyroid effects', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered, restricted use', '{}'),
('2310-17-0', 'Phosalone', '["Zolone"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered', '{}'),
('563-12-2', 'Ethion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid effects, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered', '{}'),
('55-38-9', 'Fenthion', '["Baytex"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Mosquito control"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'Restricted use', '{}'),
('2104-96-3', 'Bromophos', '["Nexion"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid effects, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation"]', 'moderate', 'Banned in many countries', '{}');