-- EPA EDSP Tier 1 Chemicals - Phase 1 (20 chemicals)
-- Source: https://www.epa.gov/endocrine-disruption/endocrine-disruptor-screening-program-tier-1-screening-determinations-and

INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('94-75-7', '2,4-Dichlorophenoxyacetic acid', '["2,4-D"]', 'Herbicide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid hormone disruption, reproductive effects', '["Pesticides", "Lawn care products", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered pesticide, restricted use', '{"docket_number": "EPA-HQ-OPP-2012-0330", "tier_1_screening": "completed", "tier_2_recommended": true, "screening_date": "2015-09-23"}'),

('71751-41-2', 'Abamectin', '["Avermectin B1"]', 'Insecticide/Acaricide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption', '["Pesticides", "Veterinary medicine", "Agricultural use"]', '["dermal", "ingestion", "inhalation"]', 'moderate', 'EPA registered pesticide', '{"docket_number": "EPA-HQ-OPP-2013-0360", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('30560-19-1', 'Acephate', '["Orthene"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurotoxicity, thyroid disruption, reproductive effects', '["Pesticides", "Agricultural use", "Residential pest control"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered pesticide', '{"docket_number": "EPA-HQ-OPP-2008-0915", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('67-64-1', 'Acetone', '["Propanone", "Dimethyl ketone"]', 'Ketone solvent', 'confirmed', '["reproductive"]', 'Reproductive effects at high doses', '["Nail polish remover", "Paint thinner", "Industrial solvent", "Cleaning products"]', '["inhalation", "dermal", "ingestion"]', 'low', 'Generally recognized as safe (GRAS) at low levels', '{"docket_number": "EPA-HQ-OPP-2009-0634", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('1912-24-9', 'Atrazine', '["AAtrex"]', 'Triazine herbicide', 'confirmed', '["reproductive", "thyroid", "adrenal"]', 'Reproductive toxicity, thyroid disruption, hormonal imbalances, linked to birth defects', '["Herbicides", "Agricultural runoff", "Drinking water contamination", "Lawn care"]', '["ingestion", "dermal", "inhalation"]', 'moderate', 'EPA registered herbicide, banned in EU, restricted in some US states', '{"docket_number": "EPA-HQ-OPP-2013-0266", "tier_1_screening": "completed", "tier_2_recommended": true, "notes": "One of most studied EDCs"}'),

('1861-40-1', 'Benfluralin', '["Balan", "Benefin"]', 'Dinitroaniline herbicide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Herbicides", "Agricultural use", "Turf management"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered herbicide', '{"docket_number": "EPA-HQ-OPP-2011-0931", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('82657-04-3', 'Bifenthrin', '["Talstar", "Brigade"]', 'Pyrethroid insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, neurotoxicity', '["Insecticides", "Residential pest control", "Agricultural use", "Termite treatment"]', '["dermal", "inhalation", "ingestion"]', 'high', 'EPA registered pesticide, restricted use', '{"docket_number": "EPA-HQ-OPP-2010-0384", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('133-06-2', 'Captan', '["Orthocide", "Captanex"]', 'Fungicide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption, potential carcinogen', '["Fungicides", "Agricultural use", "Fruit and vegetable treatment"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered fungicide', '{"docket_number": "EPA-HQ-OPP-2013-0296", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('63-25-2', 'Carbaryl', '["Sevin"]', 'Carbamate insecticide', 'confirmed', '["thyroid", "reproductive", "adrenal"]', 'Thyroid disruption, reproductive effects, neurotoxicity', '["Insecticides", "Garden products", "Pet flea treatments", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered pesticide', '{"docket_number": "EPA-HQ-OPP-2010-0230", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('1563-66-2', 'Carbofuran', '["Furadan"]', 'Carbamate insecticide/nematicide', 'confirmed', '["thyroid", "reproductive"]', 'Severe neurotoxicity, thyroid disruption, reproductive effects', '["Pesticides", "Agricultural use (restricted)", "Soil treatment"]', '["ingestion", "dermal", "inhalation"]', 'moderate', 'EPA cancelled most uses, highly restricted', '{"docket_number": "EPA-HQ-OPP-2009-0634", "tier_1_screening": "completed", "tier_2_recommended": true, "notes": "Highly toxic"}'),

('1897-45-6', 'Chlorothalonil', '["Bravo", "Daconil"]', 'Organochlorine fungicide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, kidney toxicity, potential carcinogen', '["Fungicides", "Agricultural use", "Turf management", "Golf courses"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered fungicide, banned in EU (2019)', '{"docket_number": "EPA-HQ-OPP-2011-0840", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('2921-88-2', 'Chlorpyrifos', '["Dursban", "Lorsban"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurodevelopmental effects, thyroid disruption, reproductive toxicity, linked to ADHD in children', '["Pesticides", "Agricultural use", "Formerly in residential pest control"]', '["ingestion", "inhalation", "dermal"]', 'moderate', 'Residential use banned (2000), agricultural use banned (2021)', '{"docket_number": "EPA-HQ-OPP-2008-0850", "tier_1_screening": "completed", "tier_2_recommended": true, "notes": "Significant neurotoxic effects"}'),

('68359-37-5', 'Cyfluthrin', '["Baythroid", "Tempo"]', 'Pyrethroid insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects, neurotoxicity', '["Insecticides", "Residential pest control", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered pesticide', '{"docket_number": "EPA-HQ-OPP-2010-0684", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('52315-07-8', 'Cypermethrin', '["Demon", "Cynoff"]', 'Pyrethroid insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, neurotoxicity', '["Insecticides", "Residential pest control", "Agricultural use", "Mosquito control"]', '["dermal", "inhalation", "ingestion"]', 'high', 'EPA registered pesticide', '{"docket_number": "EPA-HQ-OPP-2012-0167", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('1861-32-1', 'Dimethyl tetrachloroterephthalate', '["DCPA", "Dacthal"]', 'Herbicide', 'confirmed', '["thyroid"]', 'Thyroid disruption, developmental effects', '["Herbicides", "Agricultural use", "Turf management"]', '["dermal", "ingestion", "inhalation"]', 'high', 'EPA emergency suspension (2024) due to thyroid risks', '{"docket_number": "EPA-HQ-OPP-2011-0374", "tier_1_screening": "completed", "tier_2_recommended": false, "notes": "Emergency suspension 2024"}'),

('333-41-5', 'Diazinon', '["Spectracide"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurotoxicity, thyroid disruption, reproductive effects', '["Pesticides", "Agricultural use", "Formerly in residential pest control"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'Residential use phased out (2004), agricultural use restricted', '{"docket_number": "EPA-HQ-OPP-2008-0351", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('1194-65-6', 'Dichlobenil', '["Casoron"]', 'Herbicide', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Herbicides", "Aquatic weed control", "Rights-of-way"]', '["dermal", "ingestion", "inhalation"]', 'low', 'EPA registered herbicide, restricted use', '{"docket_number": "EPA-HQ-OPP-2012-0395", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('60-51-5', 'Dimethoate', '["Cygon", "Dimate"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurotoxicity, thyroid disruption, reproductive effects', '["Pesticides", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered pesticide, banned in EU', '{"docket_number": "EPA-HQ-OPP-2009-0059", "tier_1_screening": "completed", "tier_2_recommended": true}'),

('759-94-4', 'EPTC', '["Eptam"]', 'Thiocarbamate herbicide', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Herbicides", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered herbicide', '{"docket_number": "EPA-HQ-OPP-2012-0720", "tier_1_screening": "completed", "tier_2_recommended": false}'),

('66230-04-4', 'Esfenvalerate', '["Asana"]', 'Pyrethroid insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects, neurotoxicity', '["Insecticides", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'high', 'EPA registered pesticide, restricted use', '{"docket_number": "EPA-HQ-OPP-2009-0301", "tier_1_screening": "completed", "tier_2_recommended": true}');
