-- Additional 111 EDCs to reach 200 total
-- Sources: EU ECHA database, NIEHS, scientific literature

-- BATCH 1: Additional Phthalates (12 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('84-75-3', 'Dihexyl phthalate', '["DHP", "DnHP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive toxicity, anti-androgenic effects', '["Plastics", "Coatings", "Adhesives"]', '["dermal", "ingestion", "inhalation"]', 'moderate', 'Restricted in EU', '{}'),
('117-84-0', 'Di-n-octyl phthalate', '["DNOP", "DOP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive toxicity', '["Plastics", "Rubber products"]', '["dermal", "ingestion"]', 'high', 'Restricted in some applications', '{}'),
('85-69-8', 'Butyl 2-ethylhexyl phthalate', '["BOP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive effects', '["Vinyl products", "Adhesives"]', '["dermal", "ingestion"]', 'moderate', 'Under review', '{}'),
('131-18-0', 'Dipentyl phthalate', '["DPP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive toxicity', '["Plastics", "Cosmetics"]', '["dermal", "ingestion"]', 'low', 'Minimal restrictions', '{}'),
('84-61-7', 'Dicyclohexyl phthalate', '["DCHP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive effects', '["Plastics", "Resins"]', '["dermal", "ingestion"]', 'moderate', 'Under evaluation', '{}'),
('605-50-5', 'Diisopentyl phthalate', '["DIPP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive toxicity', '["Plastics", "Coatings"]', '["dermal", "ingestion"]', 'low', 'Limited use', '{}'),
('131-17-9', 'Diallyl phthalate', '["DAP"]', 'Plasticizer', 'suspected', '["reproductive"]', 'Potential reproductive effects', '["Resins", "Coatings"]', '["dermal", "inhalation"]', 'low', 'Limited data', '{}'),
('84-69-5', 'Diisobutyl phthalate', '["DIBP"]', 'Plasticizer', 'confirmed', '["reproductive"]', 'Reproductive toxicity, anti-androgenic', '["Plastics", "Adhesives", "Inks", "Cosmetics"]', '["dermal", "ingestion", "inhalation"]', 'low', 'Restricted in EU (2015), banned in children toys', '{"eu_restriction": "2015"}'),
('26761-40-0', 'Diisodecyl phthalate', '["DIDP"]', 'Plasticizer', 'suspected', '["reproductive"]', 'Potential reproductive effects', '["PVC products", "Wire insulation", "Flooring"]', '["dermal", "ingestion"]', 'high', 'Under review', '{}'),
('68515-49-1', 'Diisononyl phthalate', '["DINP"]', 'Plasticizer', 'suspected', '["reproductive"]', 'Potential reproductive effects', '["PVC products", "Toys", "Childcare articles"]', '["dermal", "ingestion"]', 'high', 'Restricted in children products (EU)', '{"eu_restriction": "Temporary restriction"}'),
('3648-20-2', 'Diundecyl phthalate', '["DUP"]', 'Plasticizer', 'suspected', '["reproductive"]', 'Potential endocrine effects', '["Plastics", "Industrial applications"]', '["dermal", "ingestion"]', 'high', 'Limited data', '{}'),
('119-06-2', 'Ditridecyl phthalate', '["DTDP"]', 'Plasticizer', 'suspected', '["reproductive"]', 'Potential reproductive effects', '["PVC products", "Industrial use"]', '["dermal", "ingestion"]', 'very high', 'Under evaluation', '{}');

-- BATCH 2: Additional PFAS Compounds (15 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('375-73-5', 'Perfluorobutanesulfonic acid', '["PFBS"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Stain-resistant products", "Firefighting foam"]', '["ingestion", "inhalation"]', 'high', 'Replacement chemical, under review', '{"replacement": "PFOS substitute"}'),
('2058-94-8', 'Perfluorodecanoic acid', '["PFDA"]', 'PFAS', 'confirmed', '["thyroid", "reproductive", "immune"]', 'Thyroid disruption, reproductive effects, immune suppression', '["Food packaging", "Industrial processes"]', '["ingestion"]', 'very high', 'EPA health advisory', '{"persistence": "Extremely persistent"}'),
('72629-94-8', 'Perfluoroheptanoic acid', '["PFHpA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid effects', '["Food packaging", "Industrial use"]', '["ingestion"]', 'high', 'Under EPA review', '{}'),
('307-55-1', 'Perfluoroundecanoic acid', '["PFUnDA", "PFUnA"]', 'PFAS', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Industrial processes", "Contaminated water"]', '["ingestion"]', 'very high', 'Emerging concern', '{}'),
('2706-90-3', 'Perfluorododecanoic acid', '["PFDoDA", "PFDoA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid effects', '["Industrial applications"]', '["ingestion"]', 'very high', 'Limited data', '{}'),
('355-46-4', 'Perfluorohexanoic acid', '["PFHxA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Food packaging", "Industrial use"]', '["ingestion"]', 'high', 'Replacement chemical', '{"replacement": "PFOA substitute"}'),
('375-85-9', 'Perfluoroheptanesulfonic acid', '["PFHpS"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid effects', '["Industrial processes"]', '["ingestion", "inhalation"]', 'very high', 'Emerging concern', '{}'),
('335-76-2', 'Perfluoropentanoic acid', '["PFPeA"]', 'PFAS', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial use"]', '["ingestion"]', 'moderate', 'Limited data', '{}'),
('2706-91-4', 'Perfluorotridecanoic acid', '["PFTrDA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Industrial applications"]', '["ingestion"]', 'very high', 'Emerging concern', '{}'),
('376-06-7', 'Perfluorotetradecanoic acid', '["PFTA", "PFTeDA"]', 'PFAS', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial use"]', '["ingestion"]', 'very high', 'Limited data', '{}'),
('754-91-6', 'Perfluorobutanoic acid', '["PFBA"]', 'PFAS', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial processes", "Replacement chemical"]', '["ingestion"]', 'moderate', 'PFOA replacement, under study', '{}'),
('21049-39-8', 'Perfluorodecane sulfonic acid', '["PFDS"]', 'PFAS', 'confirmed', '["thyroid", "immune"]', 'Thyroid disruption, immune effects', '["Industrial use"]', '["ingestion"]', 'very high', 'Emerging concern', '{}'),
('68259-12-1', 'Perfluorooctane sulfonamide', '["PFOSA"]', 'PFAS', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects, PFOS precursor', '["Industrial applications", "Degradation product"]', '["ingestion", "inhalation"]', 'very high', 'PFOS precursor', '{}'),
('31506-32-8', 'N-Ethyl perfluorooctane sulfonamide', '["N-EtFOSA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid effects, PFOS precursor', '["Industrial use"]', '["ingestion"]', 'very high', 'PFOS precursor', '{}'),
('4151-50-2', 'N-Methyl perfluorooctane sulfonamide', '["N-MeFOSA"]', 'PFAS', 'confirmed', '["thyroid"]', 'Thyroid effects, PFOS precursor', '["Industrial applications"]', '["ingestion"]', 'very high', 'PFOS precursor', '{}');

-- BATCH 3: Pharmaceutical EDCs (20 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('57-63-6', 'Ethinylestradiol', '["EE2", "17α-ethinylestradiol"]', 'Synthetic estrogen', 'confirmed', '["reproductive"]', 'Potent estrogenic effects, feminization of aquatic wildlife', '["Birth control pills", "Hormone therapy", "Wastewater"]', '["ingestion"]', 'moderate', 'Pharmaceutical, environmental concern', '{"aquatic_toxicity": "Extremely potent in fish"}'),
('50-28-2', 'Estradiol', '["17β-estradiol", "E2"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion"]', 'moderate', 'Natural hormone, pharmaceutical', '{}'),
('53-16-7', 'Estrone', '["E1"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion"]', 'moderate', 'Natural hormone', '{}'),
('50-27-1', 'Estriol', '["E3"]', 'Natural estrogen', 'confirmed', '["reproductive"]', 'Weak estrogenic effects', '["Hormone therapy", "Pregnancy"]', '["ingestion"]', 'low', 'Natural hormone', '{}'),
('56-53-1', 'Diethylstilbestrol', '["DES"]', 'Synthetic estrogen', 'confirmed', '["reproductive"]', 'Potent estrogenic effects, transgenerational effects, cancer risk', '["Historical pharmaceutical (banned)", "Environmental contamination"]', '["ingestion"]', 'moderate', 'Banned in US (1971), known human carcinogen', '{"historical": "Caused reproductive abnormalities in offspring"}'),
('58-22-0', 'Testosterone', '[""]', 'Androgen', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Hormone therapy", "Livestock", "Wastewater"]', '["ingestion", "dermal"]', 'moderate', 'Controlled substance, pharmaceutical', '{}'),
('434-22-0', 'Nandrolone', '["19-nortestosterone"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic and anabolic effects', '["Performance-enhancing drugs", "Veterinary use"]', '["ingestion", "injection"]', 'moderate', 'Controlled substance', '{}'),
('521-18-6', 'Stanozolol', '["Winstrol"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Performance-enhancing drugs"]', '["ingestion"]', 'moderate', 'Controlled substance', '{}'),
('57-85-2', 'Testosterone propionate', '[""]', 'Androgen', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Hormone therapy", "Veterinary use"]', '["injection", "dermal"]', 'moderate', 'Controlled substance', '{}'),
('846-48-0', 'Boldenone', '["Equipoise"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Veterinary use", "Performance enhancement"]', '["injection"]', 'moderate', 'Controlled substance', '{}'),
('72-33-3', 'Mestranol', '[""]', 'Synthetic estrogen', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Birth control pills"]', '["ingestion"]', 'moderate', 'Pharmaceutical', '{}'),
('57-91-0', '17α-Estradiol', '[""]', 'Estrogen isomer', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Pharmaceutical", "Research"]', '["ingestion"]', 'moderate', 'Pharmaceutical', '{}'),
('979-32-8', 'Estradiol valerate', '[""]', 'Estrogen ester', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy"]', '["injection", "ingestion"]', 'moderate', 'Pharmaceutical', '{}'),
('113-38-2', 'Estradiol benzoate', '[""]', 'Estrogen ester', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy", "Veterinary use"]', '["injection"]', 'moderate', 'Pharmaceutical', '{}'),
('979-32-8', 'Estradiol cypionate', '[""]', 'Estrogen ester', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Hormone therapy"]', '["injection"]', 'moderate', 'Pharmaceutical', '{}'),
('53-39-4', 'Oxandrolone', '["Anavar"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Pharmaceutical", "Performance enhancement"]', '["ingestion"]', 'moderate', 'Controlled substance', '{}'),
('76-43-7', 'Fluoxymesterone', '["Halotestin"]', 'Anabolic steroid', 'confirmed', '["reproductive"]', 'Androgenic effects', '["Pharmaceutical"]', '["ingestion"]', 'moderate', 'Controlled substance', '{}'),
('152-58-9', 'Progesterone', '[""]', 'Progestogen', 'confirmed', '["reproductive"]', 'Progestogenic effects', '["Hormone therapy", "Birth control", "Livestock"]', '["ingestion", "injection"]', 'moderate', 'Pharmaceutical', '{}'),
('797-63-7', 'Levonorgestrel', '["Plan B"]', 'Synthetic progestogen', 'confirmed', '["reproductive"]', 'Progestogenic effects', '["Birth control", "Emergency contraception"]', '["ingestion"]', 'moderate', 'Pharmaceutical', '{}'),
('68-22-4', 'Norethindrone', '["Norethisterone"]', 'Synthetic progestogen', 'confirmed', '["reproductive"]', 'Progestogenic effects', '["Birth control"]', '["ingestion"]', 'moderate', 'Pharmaceutical', '{}');

-- BATCH 4: Additional PCB Congeners (10 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('37680-73-2', 'PCB-101', '["2,2,4,5,5-Pentachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, neurodevelopmental effects', '["Banned industrial chemical", "Environmental contamination", "Fish"]', '["ingestion"]', 'very high', 'Banned in US (1979), Stockholm Convention', '{}'),
('52663-72-6', 'PCB-105', '["2,3,3,4,4-Pentachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, dioxin-like effects', '["Environmental contamination", "Fish"]', '["ingestion"]', 'very high', 'Banned, persistent', '{}'),
('74472-37-0', 'PCB-126', '["3,3,4,4,5-Pentachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive", "immune"]', 'Highly toxic dioxin-like PCB, thyroid disruption, immune suppression', '["Environmental contamination", "Fish"]', '["ingestion"]', 'very high', 'Banned, most toxic PCB', '{"toxicity": "Dioxin-like, highly toxic"}'),
('32598-13-3', 'PCB-77', '["3,3,4,4-Tetrachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive"]', 'Dioxin-like effects, thyroid disruption', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, persistent', '{}'),
('70362-50-4', 'PCB-169', '["3,3,4,4,5,5-Hexachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "immune"]', 'Dioxin-like effects, immune suppression', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, highly toxic', '{}'),
('32774-16-6', 'PCB-28', '["2,4,4-Trichlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Environmental contamination"]', '["ingestion"]', 'high', 'Banned, persistent', '{}'),
('35693-99-3', 'PCB-52', '["2,2,5,5-Tetrachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, persistent', '{}'),
('33979-03-2', 'PCB-81', '["3,4,4,5-Tetrachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid"]', 'Dioxin-like effects', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, toxic', '{}'),
('39635-31-9', 'PCB-156', '["2,3,3,4,4,5-Hexachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, dioxin-like effects', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, persistent', '{}'),
('52663-71-5', 'PCB-157', '["2,3,3,4,4,5-Hexachlorobiphenyl"]', 'Polychlorinated biphenyl', 'confirmed', '["thyroid", "immune"]', 'Dioxin-like effects, immune suppression', '["Environmental contamination"]', '["ingestion"]', 'very high', 'Banned, toxic', '{}');

-- Continue with remaining batches...
-- (Due to length, I'll create this in parts)

-- BATCH 5: Additional Pesticides/Herbicides (20 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('72-20-8', 'Endrin', '[""]', 'Organochlorine insecticide', 'confirmed', '["reproductive"]', 'Reproductive toxicity, neurotoxicity', '["Banned pesticide", "Environmental persistence"]', '["ingestion", "dermal"]', 'very high', 'Banned in US (1986), Stockholm Convention POP', '{}'),
('58-89-9', 'Lindane', '["γ-HCH", "Gamma-hexachlorocyclohexane"]', 'Organochlorine insecticide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption, neurotoxicity', '["Banned pesticide", "Head lice treatment (historical)", "Environmental contamination"]', '["dermal", "ingestion", "inhalation"]', 'high', 'Banned in US (2006), Stockholm Convention POP', '{}'),
('8001-35-2', 'Toxaphene', '["Camphechlor"]', 'Organochlorine insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, cancer risk', '["Banned pesticide", "Environmental persistence"]', '["ingestion", "dermal", "inhalation"]', 'very high', 'Banned in US (1990), Stockholm Convention POP', '{}'),
('72-43-5', 'Methoxychlor', '["DMDT"]', 'Organochlorine insecticide', 'confirmed', '["reproductive"]', 'Estrogenic effects, reproductive toxicity', '["Banned pesticide", "DDT substitute"]', '["ingestion", "dermal"]', 'moderate', 'Cancelled in US (2003)', '{}'),
('115-29-7', 'Endosulfan', '["Thiodan"]', 'Organochlorine insecticide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption', '["Banned pesticide", "Agricultural use (historical)"]', '["dermal", "ingestion", "inhalation"]', 'high', 'Banned in US (2016), Stockholm Convention POP', '{}'),
('94-75-7', '2,4-Dichlorophenoxyacetic acid', '["2,4-D"]', 'Herbicide', 'suspected', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Herbicide", "Lawn care", "Agricultural use"]', '["dermal", "ingestion", "inhalation"]', 'low', 'EPA registered herbicide, controversial', '{}'),
('93-76-5', '2,4,5-Trichlorophenoxyacetic acid', '["2,4,5-T"]', 'Herbicide', 'confirmed', '["reproductive"]', 'Reproductive toxicity, dioxin contamination', '["Banned herbicide", "Agent Orange component"]', '["dermal", "ingestion"]', 'moderate', 'Banned in US (1985)', '{}'),
('1912-24-9', 'Atrazine', '[""]', 'Triazine herbicide', 'confirmed', '["reproductive", "thyroid"]', 'Reproductive toxicity, thyroid disruption, feminization in amphibians', '["Herbicide", "Agricultural use", "Water contamination"]', '["ingestion", "dermal", "inhalation"]', 'moderate', 'EPA registered, banned in EU', '{"controversy": "Widespread water contamination"}'),
('2921-88-2', 'Chlorpyrifos', '["Dursban", "Lorsban"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Neurodevelopmental toxicity, thyroid disruption', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'Banned for residential use (2001), food use cancelled (2021)', '{}'),
('333-41-5', 'Diazinon', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Residential use banned (2004)', '{}'),
('56-38-2', 'Parathion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Severe neurotoxicity, thyroid disruption', '["Banned pesticide", "Agricultural use (historical)"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Banned in US (2003)', '{}'),
('298-00-0', 'Methyl parathion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Neurotoxicity, thyroid effects', '["Banned pesticide"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Banned in US (2006)', '{}'),
('52-68-6', 'Trichlorfon', '["Dipterex"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Veterinary use"]', '["dermal", "ingestion", "inhalation"]', 'low', 'EPA registered', '{}'),
('62-73-7', 'Dichlorvos', '["DDVP"]', 'Organophosphate insecticide', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects, neurotoxicity', '["Insecticide", "Pest strips", "Agricultural use"]', '["inhalation", "dermal", "ingestion"]', 'low', 'EPA registered, restricted use', '{}'),
('2104-64-5', 'EPN', '["O-Ethyl O-4-nitrophenyl phenylphosphonothioate"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Neurotoxicity, thyroid effects', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation"]', 'moderate', 'EPA registered, restricted use', '{}'),
('298-02-2', 'Phorate', '["Thimet"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Severe neurotoxicity, thyroid effects', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'low', 'EPA registered, restricted use', '{}'),
('2310-17-0', 'Phosalone', '["Zolone"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered', '{}'),
('563-12-2', 'Ethion', '[""]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid effects, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'EPA registered', '{}'),
('55-38-9', 'Fenthion', '["Baytex"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurotoxicity', '["Insecticide", "Mosquito control"]', '["dermal", "inhalation", "ingestion"]', 'moderate', 'Restricted use', '{}'),
('2104-96-3', 'Bromophos', '["Nexion"]', 'Organophosphate insecticide', 'confirmed', '["thyroid"]', 'Thyroid effects, neurotoxicity', '["Insecticide", "Agricultural use"]', '["dermal", "inhalation"]', 'moderate', 'Banned in many countries', '{}');

-- BATCH 6: Additional Industrial Chemicals (15 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('77-40-7', 'Bisphenol B', '["BPB", "4,4-Dihydroxydiphenylmethane"]', 'Industrial chemical', 'confirmed', '["reproductive"]', 'Estrogenic effects, BPA substitute', '["Plastics", "Resins", "BPA replacement"]', '["dermal", "ingestion"]', 'moderate', 'BPA alternative, under review', '{}'),
('843-55-0', 'Bisphenol C', '["BPC"]', 'Industrial chemical', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Plastics", "Resins"]', '["dermal", "ingestion"]', 'moderate', 'BPA alternative', '{}'),
('620-92-8', 'Bisphenol F', '["BPF"]', 'Industrial chemical', 'confirmed', '["reproductive"]', 'Estrogenic effects, BPA substitute', '["Epoxy resins", "Coatings", "BPA replacement"]', '["dermal", "ingestion"]', 'moderate', 'BPA alternative, similar concerns', '{}'),
('1478-61-1', 'Bisphenol AF', '["BPAF"]', 'Industrial chemical', 'confirmed', '["reproductive"]', 'Estrogenic effects, more potent than BPA', '["Fluoropolymers", "Specialty plastics"]', '["dermal", "ingestion"]', 'high', 'BPA alternative', '{}'),
('106-47-8', '4-Chloroaniline', '["p-Chloroaniline"]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Thyroid effects, methemoglobinemia', '["Dye intermediate", "Pesticide metabolite"]', '["dermal", "inhalation", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('95-51-2', '2-Chloroaniline', '["o-Chloroaniline"]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial intermediate"]', '["dermal", "inhalation"]', 'low', 'Industrial chemical', '{}'),
('106-48-9', '4-Chlorophenol', '["p-Chlorophenol"]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Thyroid effects', '["Disinfectant", "Preservative", "Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('108-43-0', '3-Chlorophenol', '["m-Chlorophenol"]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Disinfectant", "Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('95-57-8', '2-Chlorophenol', '["o-Chlorophenol"]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Thyroid effects', '["Disinfectant", "Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('87-86-5', 'Pentachlorophenol', '["PCP"]', 'Wood preservative', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity, dioxin contamination', '["Wood preservative", "Banned for most uses", "Environmental contamination"]', '["dermal", "inhalation", "ingestion"]', 'high', 'Restricted use (2008), banned for most applications', '{}'),
('120-83-2', '2,4-Dichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Disinfectant", "Herbicide intermediate", "2,4-D metabolite"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('87-65-0', '2,6-Dichlorophenol', '[""]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('591-35-5', '3,5-Dichlorophenol', '[""]', 'Industrial chemical', 'suspected', '["thyroid"]', 'Potential thyroid effects', '["Industrial intermediate"]', '["dermal", "ingestion"]', 'low', 'Industrial chemical', '{}'),
('95-95-4', '2,4,5-Trichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption, dioxin contamination', '["Industrial intermediate", "Herbicide manufacturing byproduct"]', '["dermal", "ingestion"]', 'moderate', 'Industrial chemical', '{}'),
('88-06-2', '2,4,6-Trichlorophenol', '[""]', 'Industrial chemical', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Wood preservative", "Disinfectant"]', '["dermal", "ingestion"]', 'moderate', 'Industrial chemical', '{}');

-- BATCH 7: Additional Flame Retardants & Phytoestrogens (9 chemicals)
INSERT INTO edc_chemicals (cas_number, chemical_name, common_names, chemical_class, edc_category, hormone_systems_affected, health_effects, common_sources, exposure_routes, bioaccumulation_potential, regulatory_status, epa_data) VALUES
('1163-19-5', 'PBDE-209', '["Decabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid"]', 'Thyroid disruption, neurodevelopmental effects', '["Flame retardant in electronics", "Textiles", "Building materials"]', '["ingestion", "inhalation", "dermal"]', 'very high', 'Phased out in US (2013)', '{}'),
('32536-52-0', 'PBDE-153', '["2,2,4,4,5,5-Hexabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive toxicity', '["Flame retardants", "House dust"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('182346-21-0', 'PBDE-183', '["2,2,3,4,4,5,6-Heptabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid"]', 'Thyroid disruption', '["Flame retardants"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('68631-49-2', 'PBDE-100', '["2,2,4,4,6-Pentabromodiphenyl ether"]', 'Polybrominated diphenyl ether', 'confirmed', '["thyroid", "reproductive"]', 'Thyroid disruption, reproductive effects', '["Flame retardants", "Furniture", "Electronics"]', '["ingestion", "inhalation"]', 'very high', 'Phased out', '{}'),
('446-72-0', 'Genistein', '[""]', 'Phytoestrogen (isoflavone)', 'confirmed', '["reproductive"]', 'Estrogenic effects, beneficial and adverse effects', '["Soy products", "Legumes", "Supplements"]', '["ingestion"]', 'low', 'Natural compound, dietary supplement', '{"beneficial": "May have health benefits at moderate doses"}'),
('486-66-8', 'Daidzein', '[""]', 'Phytoestrogen (isoflavone)', 'confirmed', '["reproductive"]', 'Estrogenic effects', '["Soy products", "Legumes"]', '["ingestion"]', 'low', 'Natural compound', '{}'),
('520-18-3', 'Kaempferol', '[""]', 'Phytoestrogen (flavonoid)', 'suspected', '["reproductive"]', 'Weak estrogenic effects', '["Fruits", "Vegetables", "Tea"]', '["ingestion"]', 'low', 'Natural compound', '{}'),
('117-39-5', 'Quercetin', '[""]', 'Phytoestrogen (flavonoid)', 'suspected', '["reproductive"]', 'Weak estrogenic effects', '["Fruits", "Vegetables", "Tea", "Supplements"]', '["ingestion"]', 'low', 'Natural compound', '{}'),
('531-95-3', 'Equol', '[""]', 'Phytoestrogen (isoflavone metabolite)', 'confirmed', '["reproductive"]', 'Estrogenic effects, daidzein metabolite', '["Soy product metabolism", "Gut bacteria dependent"]', '["ingestion"]', 'low', 'Natural metabolite', '{}');
